#pragma once

enum MainPanelCtrlIds {
    CID_MAIN_PANEL = wxID_HIGHEST + 101,
    CID_PLAY,
    CID_PAUSE,
    CID_STOP,
    CID_PREV,
    CID_NEXT,
    CID_MUTE,
    CID_OPEN_FILE,

    CID_TOGGLE_BROWSER,
    CID_TOGGLE_LYRIC,
    CID_TOGGLE_EQ,
    CID_TOGGLE_PLAYLIST,

    CID_PLAY_LIST,
    CID_SEARCH_RESULT,
    CID_LYRIC,

    CID_ABOUT,
    CID_FEEDBACK,

    CID_MINIMIZE,
    CID_MINIMODE,
    CID_EXIT,
    CID_PROGRESS,
    CID_VOLUME,
    CID_VISUAL,
    CID_ICON,
    CID_INFO,
    CID_LED,
    CID_STEREO,
    CID_STATUS,

    CID_SERACH_EDIT, // 播放列表窗口搜索列表搜索控件文本框
};

enum OOPMainMenuId {
    OMM_LOWER_BOUND = wxID_HIGHEST + 200,
    OMM_PLAYER_OPTIONS = OMM_LOWER_BOUND,

    OMM_LINKS_WEBSITE,
    OMM_LINKS_FORUM,

    OOM_PLAY_PAUSE,
    OOM_STOP,
    OOM_PREV,
    OOM_NEXT,
    OOM_VOLUME_UP,
    OOM_VOLUME_DOWN,
    OOM_MUTE,

    OMM_UPPER_BOUND,
};

enum OOPlayerPlayMode {
    PLAY_MODE_LOWER_BOUND = wxID_HIGHEST + 300,
    PLAY_MODE_SINGLE,
    PLAY_MODE_SINGLE_RECYCLE,
    PLAY_MODE_BY_LIST,
    PLAY_MODE_LIST_RECYCLE,
    PLAY_MODE_LIST_RANDOM,
    PLAY_MODE_UPPER_BOUND,
};

enum OOPPlayListPanelMenu {
    OPLM_LOWER_BOUND = wxID_HIGHEST + 400,

    OPLM_PLAY_SELECTED = OPLM_LOWER_BOUND,
    OPLM_SEP1,
    OPLM_FILE_PROPERTIES,
    OPLM_SEP2,

    OPLM_DELETE,
    OPLM_DELETE_FILE,
    OPLM_RENAME_FILE,
    OPLM_LOCATE_FILE,

    OPLM_SEP3,
    OPLM_PLAYLIST_OPTIONS,

    //---------------------------

    OPLM_RENAME_LOWER_BOUND,
    OPLM_RENAME_SINGER_FIRST = OPLM_RENAME_LOWER_BOUND,
    OPLM_RENAME_SONGNAME_FIRST,
    OPLM_RENAME_SONGNAME_ONLY,
    OPLM_RENAME_UPPER_BOUND = OPLM_RENAME_SONGNAME_ONLY,
};

enum OOPToolBarMenus {
    OTBM_MENU = wxID_HIGHEST + 600,

    OTBM_ADD_FILE,
    OTBM_ADD_FOLDER_RECURSIVE,
    OTBM_ADD_FOLDER,

    OTBM_DELETE_DUPLICATED,
    OTBM_DELETE_WRONG_FILE,
    OTBM_DELETE_SEP_1,
    OTBM_DELETE_ALL,
    OTBM_DELETE_SEP_2,
    OTBM_DELETE_FILE, // HASH-MAP Hacks

    OTBM_LIST_OPEN,
    OTBM_LIST_SAVE,
    OTBM_LIST_NEW,

    OTBM_SORT_BY_TITLE,
    OTBM_SORT_BY_PATH,
    OTBM_SORT_BY_ALBUM,
    OTBM_SORT_BY_LENGTH,
    OTBM_SORT_BY_PLAY_COUNT,
    OTBM_SORT_BY_ADD_TIME,

    OTBM_LOCATE_SHOW_DIALOG,
    OTBM_LOCATE_FIND_NEXT,

    OTBM_SELECT_ALL,
    OTBM_SELECT_NONE,
    OTBM_SELECT_REVERSE,
};

enum OOPLyricMenuIds {
    OLRCM_LOWER_BOUND = 200,
    OLRCM_SEARCH = OLRCM_LOWER_BOUND,
    OLRCM_ASSOCIATE_LOCAL_FILE,

    OLRCM_SEP1,

    OLRCM_COPY_LRC,
    OLRCM_REMOVE_LRC,
    OLRCM_RELOAD_LRC,

    OLRCM_SEP2,

    OLRCM_SC2TC,
    OLRCM_TC2SC,

    OLRCM_ONTOP,

    OLRCM_LRC_OPTIONS,
    OLRCM_UPPER_BOUND
};
